### PR TITLE
[WIP] add rock3a support

### PR DESCRIPTION
**Pull request by amazingfate**

### CODE REVIEW

**Comment by GuEe-GUI** [comment]
Hello, PCIE20 is ok? https://github.com/jaredmcneill/quartz64_uefi/issues/53

**Comment by amazingfate** [comment]
I remember pcie20 and pcie30 can't work at the same time last year. And I can boot fedora iso which can detect m.2 wifi. I don't know what's the status now.

**Comment by amazingfate** [comment]
This pr is old and not good to merge, close.

**Comment by GuEe-GUI** [comment]
> I remember pcie20 and pcie30 can't work at the same time last year. And I can boot fedora iso which can detect m.2 wifi. I don't know what's the status now.

So the PCIE20 can work in this UEFI (quartz64_uefi)? sorry, I just confirming.

**Pull request closed without merging**
