### PR TITLE
Firefly roc356x install doc

### PR DESCRIPTION
**Pull request by andreamtp**
Follow up from PR #47 
Due to change in the branch name with a more significant one, old PR has been closed and a new one is setup

### CODE REVIEW

**Comment by jaredmcneill** [comment]
LGTM. Probably we could make these instructions generic, but lets do that in a separate change.

**Comment by dgwynne** [comment]
> LGTM. Probably we could make these instructions generic, but lets do that in a separate change.

my experience with the roc-rk356x-pc has been pretty unique so far. maybe it's the SPI flash complicating things, but it's been different enough to every other board i've played with so far that having separate instructions for them makes sense to me.

**Comment by jaredmcneill** [comment]
Can you rebase this change to resolve conflicts?

**Comment by jaredmcneill** [comment]
> > LGTM. Probably we could make these instructions generic, but lets do that in a separate change.
> 
> my experience with the roc-rk356x-pc has been pretty unique so far. maybe it's the SPI flash complicating things, but it's been different enough to every other board i've played with so far that having separate instructions for them makes sense to me.

There are three cases that I think covers all of the boards we've had to deal with so far:
- Removable SD card
- Removable eMMC
- Non-removable eMMC

Eventually we may want to support UEFI in SPI, but it's not there today.

**Comment by andreamtp** [comment]
> Can you rebase this change to resolve conflicts?

Done

**Pull request merged**
