### PR TITLE
Add Orange Pi 3B platform

### PR DESCRIPTION
**Pull request by mariobalanica**
Tested to be working:
  - UART
  - HDMI
  - USB
  - eMMC
  - GMAC (in NetBSD and VMware ESXi)
  - PCIe
  - PMIC & CPU voltage regulator

Limitations:
  - SD card gets detected but var store changes don't persist.
  - eMMC speed is limited.
  - M.2 PCIe only works with low power devices (i.e. no NVME) because the 3.3V line is too weak. Could be an issue with my unit or the hardware revision (v1.1), unconfirmed yet.
  - RTC provided by RK809 is not supported.

### CODE REVIEW

**Comment by rpardini** [comment]
> * M.2 PCIe only works with low power devices (i.e. no NVME) because the 3.3V line is too weak. Could be an issue with my unit or the hardware revision (v1.1), unconfirmed yet.

Hey @mariobalanica sorry to pester, but do you remember what device _did_ work? I'm about to try with a (hand-held-down) 2280 NVMe just for kicks, but was wondering if a 2230/2242 SATA-600 would work, I also have the 1.1 board revision.

**Comment by mariobalanica** [comment]
@rpardini Wi-Fi cards and a SATA controller connected through a powered PCIe riser worked fine.

> but was wondering if a 2230/2242 SATA-600 would work

For onboard SATA you need to disable PCIe and switch the combo PHY 2 mode.

**Comment by rpardini** [comment]
Using a 2280 WD Blue 1Tb, held down by an elastic band, works on my board, also 1.1 revision.

**Comment by PrestarLin** [comment]
> Tested to be working:
> 
> * UART
> * HDMI
> * USB
> * eMMC
> * GMAC (in NetBSD and VMware ESXi)
> * PCIe
> * PMIC & CPU voltage regulator
> 
> Limitations:
> 
> * SD card gets detected but var store changes don't persist.
> * eMMC speed is limited.
> * M.2 PCIe only works with low power devices (i.e. no NVME) because the 3.3V line is too weak. Could be an issue with my unit or the hardware revision (v1.1), unconfirmed yet.
> * RTC provided by RK809 is not supported.

my orangepi 3b isn't work when i write it to TF card,it cannot read ESC from the keyboard, Just use the img of ROC 3566EFI.img is ok(keyboard connect to the usb2.0 side of usb3.0)

**Pull request merged**
